### ISSUE TITLE
Remove the user role

### ISSUE THREAD

**Issue by michel-iamit** [dabapps/django-user-roles#7]
Is there a way to remove the user role?
I tried:

set_user_role(user_to_change, None)

and if there is a way, can you document it

(by the way, nice app!)

**Comment by iamit** [comment]
I found out that using this method it will prevent you from deleting a user, because the user is being refered by the userrole model (only tested this in sqlite, in development environment)

**Comment by iamit** [comment]
to really remove it:

    from userroles.models import UserRole

find the UserRole object with a user by a query on the field user
